[build-system]
requires = ["setuptools >=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "keras"
authors = [
    {name = "Keras team", email = "keras-users@googlegroups.com"},
]
description = "Multi-backend Keras"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "Apache License 2.0"}
dynamic = ["version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
]
dependencies = [
    "absl-py",
    "numpy",
    "rich",
    "namex",
    "h5py",
    "optree",
    "ml-dtypes",
    "packaging",
]
# For a complete development environment run: pip install -r requirements.txt

[project.urls]
Home = "https://keras.io/"
Repository = "https://github.com/keras-team/keras"

[tool.setuptools.package-dir]
"keras" = "keras/api"
"keras.src" = "keras/src"

[tool.setuptools]
packages = [
    "keras",
    "keras",
    "keras.callbacks",
    "keras.layers",
    "keras.datasets",
    "keras.datasets.boston_housing",
    "keras.datasets.cifar10",
    "keras.datasets.fashion_mnist",
    "keras.datasets.imdb",
    "keras.datasets.mnist",
    "keras.datasets.cifar100",
    "keras.datasets.california_housing",
    "keras.datasets.reuters",
    "keras._tf_keras",
    "keras._tf_keras.keras",
    "keras._tf_keras.keras.callbacks",
    "keras._tf_keras.keras.layers",
    "keras._tf_keras.keras.datasets",
    "keras._tf_keras.keras.datasets.boston_housing",
    "keras._tf_keras.keras.datasets.cifar10",
    "keras._tf_keras.keras.datasets.fashion_mnist",
    "keras._tf_keras.keras.datasets.imdb",
    "keras._tf_keras.keras.datasets.mnist",
    "keras._tf_keras.keras.datasets.cifar100",
    "keras._tf_keras.keras.datasets.california_housing",
    "keras._tf_keras.keras.datasets.reuters",
    "keras._tf_keras.keras.metrics",
    "keras._tf_keras.keras.models",
    "keras._tf_keras.keras.visualization",
    "keras._tf_keras.keras.legacy",
    "keras._tf_keras.keras.legacy.saving",
    "keras._tf_keras.keras.preprocessing",
    "keras._tf_keras.keras.preprocessing.sequence",
    "keras._tf_keras.keras.preprocessing.image",
    "keras._tf_keras.keras.preprocessing.text",
    "keras._tf_keras.keras.config",
    "keras._tf_keras.keras.export",
    "keras._tf_keras.keras.distribution",
    "keras._tf_keras.keras.ops",
    "keras._tf_keras.keras.ops.image",
    "keras._tf_keras.keras.ops.numpy",
    "keras._tf_keras.keras.ops.nn",
    "keras._tf_keras.keras.ops.linalg",
    "keras._tf_keras.keras.wrappers",
    "keras._tf_keras.keras.optimizers",
    "keras._tf_keras.keras.optimizers.schedules",
    "keras._tf_keras.keras.optimizers.legacy",
    "keras._tf_keras.keras.saving",
    "keras._tf_keras.keras.mixed_precision",
    "keras._tf_keras.keras.regularizers",
    "keras._tf_keras.keras.dtype_policies",
    "keras._tf_keras.keras.quantizers",
    "keras._tf_keras.keras.backend",
    "keras._tf_keras.keras.constraints",
    "keras._tf_keras.keras.applications",
    "keras._tf_keras.keras.applications.inception_resnet_v2",
    "keras._tf_keras.keras.applications.densenet",
    "keras._tf_keras.keras.applications.mobilenet_v2",
    "keras._tf_keras.keras.applications.resnet50",
    "keras._tf_keras.keras.applications.efficientnet",
    "keras._tf_keras.keras.applications.convnext",
    "keras._tf_keras.keras.applications.resnet",
    "keras._tf_keras.keras.applications.resnet_v2",
    "keras._tf_keras.keras.applications.efficientnet_v2",
    "keras._tf_keras.keras.applications.xception",
    "keras._tf_keras.keras.applications.nasnet",
    "keras._tf_keras.keras.applications.mobilenet",
    "keras._tf_keras.keras.applications.vgg16",
    "keras._tf_keras.keras.applications.vgg19",
    "keras._tf_keras.keras.applications.mobilenet_v3",
    "keras._tf_keras.keras.applications.imagenet_utils",
    "keras._tf_keras.keras.applications.inception_v3",
    "keras._tf_keras.keras.activations",
    "keras._tf_keras.keras.losses",
    "keras._tf_keras.keras.tree",
    "keras._tf_keras.keras.random",
    "keras._tf_keras.keras.utils",
    "keras._tf_keras.keras.utils.bounding_boxes",
    "keras._tf_keras.keras.utils.legacy",
    "keras._tf_keras.keras.initializers",
    "keras.metrics",
    "keras.models",
    "keras.visualization",
    "keras.legacy",
    "keras.legacy.saving",
    "keras.preprocessing",
    "keras.preprocessing.sequence",
    "keras.preprocessing.image",
    "keras.config",
    "keras.export",
    "keras.distribution",
    "keras.ops",
    "keras.ops.image",
    "keras.ops.numpy",
    "keras.ops.nn",
    "keras.ops.linalg",
    "keras.wrappers",
    "keras.optimizers",
    "keras.optimizers.schedules",
    "keras.optimizers.legacy",
    "keras.saving",
    "keras.mixed_precision",
    "keras.regularizers",
    "keras.dtype_policies",
    "keras.quantizers",
    "keras.backend",
    "keras.constraints",
    "keras.applications",
    "keras.applications.inception_resnet_v2",
    "keras.applications.densenet",
    "keras.applications.mobilenet_v2",
    "keras.applications.resnet50",
    "keras.applications.efficientnet",
    "keras.applications.convnext",
    "keras.applications.resnet",
    "keras.applications.resnet_v2",
    "keras.applications.efficientnet_v2",
    "keras.applications.xception",
    "keras.applications.nasnet",
    "keras.applications.mobilenet",
    "keras.applications.vgg16",
    "keras.applications.vgg19",
    "keras.applications.mobilenet_v3",
    "keras.applications.imagenet_utils",
    "keras.applications.inception_v3",
    "keras.activations",
    "keras.losses",
    "keras.tree",
    "keras.random",
    "keras.utils",
    "keras.utils.bounding_boxes",
    "keras.utils.legacy",
    "keras.initializers",
    "keras.src",
    "keras.src.trainers",
    "keras.src.trainers.data_adapters",
    "keras.src.callbacks",
    "keras.src.layers",
    "keras.src.layers.reshaping",
    "keras.src.layers.preprocessing",
    "keras.src.layers.preprocessing.image_preprocessing",
    "keras.src.layers.preprocessing.image_preprocessing.bounding_boxes",
    "keras.src.layers.attention",
    "keras.src.layers.core",
    "keras.src.layers.regularization",
    "keras.src.layers.activations",
    "keras.src.layers.normalization",
    "keras.src.layers.pooling",
    "keras.src.layers.rnn",
    "keras.src.layers.convolutional",
    "keras.src.layers.merging",
    "keras.src.datasets",
    "keras.src.metrics",
    "keras.src.models",
    "keras.src.visualization",
    "keras.src.legacy",
    "keras.src.legacy.preprocessing",
    "keras.src.legacy.saving",
    "keras.src.export",
    "keras.src.distribution",
    "keras.src.ops",
    "keras.src.wrappers",
    "keras.src.optimizers",
    "keras.src.optimizers.schedules",
    "keras.src.saving",
    "keras.src.regularizers",
    "keras.src.dtype_policies",
    "keras.src.quantizers",
    "keras.src.backend",
    "keras.src.backend.common",
    "keras.src.backend.numpy",
    "keras.src.backend.tensorflow",
    "keras.src.backend.torch",
    "keras.src.backend.torch.optimizers",
    "keras.src.backend.jax",
    "keras.src.backend.openvino",
    "keras.src.constraints",
    "keras.src.applications",
    "keras.src.activations",
    "keras.src.testing",
    "keras.src.losses",
    "keras.src.tree",
    "keras.src.random",
    "keras.src.utils",
    "keras.src.initializers",
]

[tool.setuptools.dynamic]
version = {attr = "keras.src.version.__version__"}

[tool.ruff]
line-length = 80
exclude = ["keras/src/namex"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle error
    "F",  # Pyflakes
    "I",  # isort
]
ignore = [
    "E722",  # do not use bare 'except'
    "E741",  # ambiguous variable name
    "E731",  # do not assign a `lambda` expression, use a `def`
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["E501", "F401"]  # lines too long; imported but unused
"**/random.py" = ["F401"]  # imported but unused
"examples/*" = ["I", "E"]
"guides/*" = ["I", "E", "F"]

[tool.ruff.lint.isort]
force-single-line = true
known-first-party = ["keras"]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore::ImportWarning",
    "ignore::RuntimeWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::FutureWarning",
    "ignore::UserWarning",
    # Ignore a spurious warning on tf-nightly related to save model changes.
    "ignore:Custom mask layers require a config",
]
addopts = "-vv"

# Do not run tests in the `build` folders
norecursedirs = ["build"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@abstract",
    "raise NotImplementedError",
]
omit = [
    "*/*_test.py",
    "keras/src/legacy/*",
]

[tool.coverage.run]
branch = true
omit = [
    "*/*_test.py",
    "keras/src/legacy/*",
]

